@startuml

title 

class Patate {
    variete: string
    usage: string
}

class Personne {
    id: int
    nom: string
    prenom: string
    patate: Patate
}

class Caillou {
    cher: boolean
}


@enduml


