@startuml

title c'est bien de mettre un titre

class Carotte {
    variete: string
    usage: string
}

class Personne {
    id: int
    nom: string
    prenom: string
    patate: Patate
}

class Caillou {
    cher: boolean
}


@enduml

